Repository dockstore/dockstore-ui2, pull requests merged in 2020-06, with the labels that each got.

#996 validation messages
  src/app/shared/validationMessages.model.ts
  src/app/workflow/register-workflow-modal/register-workflow-modal.component.html
  src/app/workflow/register-workflow-modal/register-workflow-modal.component.ts
Labels: bug, enhancement

#997 broken loading gif
  src/app/loginComponents/auth/auth.component.html
Labels: bug

#995 partial github app feedback
  src/app/entry/entry-file-tab/entry-file-tab.component.html
  src/app/entry/file-path.pipe.ts
  src/app/shared/pipe/pipe.module.ts
  src/app/workflow/register-workflow-modal/register-workflow-modal.component.html
Labels: enhancement

#1008 Bump jQuery version from 3.4.0 to 3.4.1
  package-lock.json
  package.json
Labels: security

#1007 Add subresource integrity to embedded content
  package.json
Labels: security

#1013 descriptor type bug
  src/app/workflow/info-tab/info-tab.service.ts
Labels: bug

#1016 show verified icon
  src/app/workflow/workflow.component.html
Labels: bug

#1015 quickstart for Mac
  src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.html
  src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.scss
  src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.spec.ts
  src/app/loginComponents/onboarding/downloadcliclient/downloadcliclient.component.ts
Labels: enhancement
